name: zero2prod
# Check https://www.digitalocean.com/docs/app-platform/#regional-availability
# for a list of all the available options.
# You can get region slugs from
# https://www.digitalocean.com/docs/platform/availability-matrix/
# They must specified lowercased.
# `fra` stands for Frankfurt (Germany - EU)
region: nyc
services:
  - name: zero2prod
    envs:
      - key: APP_DATABASE__USERNAME
        scope: RUN_AND_BUILD_TIME
        value: ${newsletter.USERNAME}
      - key: APP_DATABASE__PASSWORD
        scope: RUN_AND_BUILD_TIME
        value: ${newsletter.PASSWORD}
      - key: APP_DATABASE__HOST
        scope: RUN_AND_BUILD_TIME
        value: ${newsletter.HOSTNAME}
      - key: APP_DATABASE__PORT
        scope: RUN_AND_BUILD_TIME
        value: ${newsletter.PORT}
      - key: APP_DATABASE__DATABASE_NAME
        scope: RUN_AND_BUILD_TIME
        value: ${newsletter.DATABASE}
    image:
      registry_type: DOCKER_HUB
      registry: brunoan99
      repository: zero2prod
      tag: "0.2"
      deploy_on_push:
        enabled: true
    health_check:
      http_path: /health_check
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
